service:
  name: alexa-gender-equality-facts

plugins:
  - serverless-webpack
  - serverless-alexa-skills
  - serverless-iam-roles-per-function
provider:
  name: aws
  runtime: nodejs8.10
  cfnRole: arn:aws:iam::${env:AMAZON_ACCOUNT_ID}:role/ServerlessCloudFormationRole

custom:
  stage: ${opt:stage, self:provider.stage}  
  region: ${opt:region, self:provider.region}
  environment:
    dev:
      skill: 
        id: amzn1.ask.skill.27c671b8-dcb8-4a9f-9e81-5441859ae3b6
        englishLanguageModel:
          invocationName: gender equality facts
          intents:
            - name: HelloIntent
              samples:
                - 'yo bro'
    prod:
      skill:
        id: amzn1.ask.skill.10d13176-c252-4396-8fb6-5d255579627a
        englishLanguageModel:
          invocationName: gender equality facts
          intents:
            - name: HelloIntent
              samples:
                - 'hello'
  alexa:
    vendorId: ${env:AMAZON_VENDOR_ID}
    clientId: ${env:AMAZON_CLIENT_ID}
    clientSecret: ${env:AMAZON_CLIENT_SECRET}
    localServerPort: 9090
    skills:
      - id: ${self:custom.environment.${self:custom.stage}.skill.id}
        manifest:
          publishingInformation:
            locales:
              en-GB:
                name: "Gender Equality Facts"
              en-US:
                name: "Gender Equality Facts"
              en-CA:
                name: "Gender Equality Facts"
              en-AU:
                name: "Gender Equality Facts"
              en-IN:
                name: "Gender Equality Facts"
          apis:
            custom:
              endpoint:
                uri: arn:aws:lambda:${self:custom.region}:${env:AMAZON_ACCOUNT_ID}:function:${self:service.name}-${self:custom.stage}-alexa
          manifestVersion: '1.0'
        models:
          en-GB:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
          en-US:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
          en-CA:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
          en-AU:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
          en-IN:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
functions:
  alexa:
    handler: src/main.handler
    events:
      - alexaSkill: ${self:custom.alexa.skills.0.id}
    iamRoleStatementsName: 
      - Effect: "Allow"
        Action: 
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
        Resource: "*"