service:
  name: aws-alexa-typescript

plugins:
  - serverless-webpack
  - serverless-alexa-skills
  - serverless-iam-roles-per-function
provider:
  name: aws
  runtime: nodejs8.10
  cfnRole: arn:aws:iam::${env:AMAZON_ACCOUNT_ID}:role/ServerlessCloudFormationRole

custom:
  stage: ${opt:stage, self:provider.stage}  
  region: ${opt:region, self:provider.region}
  environment:
    dev:
      skill: 
        id: amzn1.ask.skill.921a3662-434d-4743-a078-26a82d248e8d
        englishLanguageModel:
          invocationName: serverless typescript
          intents:
            - name: HelloIntent
              samples:
                - 'yo bro'
    prod:
      skill:
        id: amzn1.ask.skill.454e193b-7bc9-4637-a3a5-7f16f230730c
        englishLanguageModel:
          invocationName: serverless typescript
          intents:
            - name: HelloIntent
              samples:
                - 'hello'
  alexa:
    vendorId: ${env:AMAZON_VENDOR_ID}
    clientId: ${env:AMAZON_CLIENT_ID}
    clientSecret: ${env:AMAZON_CLIENT_SECRET}
    localServerPort: 9090
    skills:
      - id: ${self:custom.environment.${self:custom.stage}.skill.id}
        manifest:
          publishingInformation:
            locales:
              en-GB:
                name: "My Alexa Skill"
              en-US:
                name: "My Alexa Skill"
              en-CA:
                name: "My Alexa Skill"
              en-AU:
                name: "My Alexa Skill"
              en-IN:
                name: "My Alexa Skill"
              de-DE:
                name: "Meine Alexa-Fahigkeit"
          apis:
            custom:
              endpoint:
                uri: arn:aws:lambda:${self:custom.region}:${env:AMAZON_ACCOUNT_ID}:function:${self:service.name}-${self:custom.stage}-alexa
          manifestVersion: '1.0'
        models:
          en-GB:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
          en-US:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
          en-CA:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
          en-AU:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
          en-IN:
            interactionModel:
              languageModel: ${self:custom.environment.${self:custom.stage}.skill.englishLanguageModel}
functions:
  alexa:
    handler: handler.alexa
    events:
      - alexaSkill: ${self:custom.alexa.skills.0.id}
    iamRoleStatementsName: 
      - Effect: "Allow"
        Action: 
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
        Resource: "*"